version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: map_backend_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: map_desa
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
